# Introduction to R - programming : <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/724px-R_logo.svg.png" width=100 alt="Introduction to R programming " style="float:right">

##### Q. What is the file extension of R scripts? and, How to run R scripts?
**A.** The R script files are saved with **.R** extension. 
Example : " EDA_titanic.R  "

**To run R script:**

First, open your terminal or cmd with R enviornment activated. <br>
Second, run the following command : 
<br>`Syntax : Rscript \[ filename \].R`

Example  :
```>> Rscript EDA_titanic.R```

## Input - Output :

#### print() function : 
This function is used to print text passed to it on the screen. For example : 

In [1]:
print("Welcome to R programming!")

[1] "Welcome to R programming!"


#### readline() function:
This function is used for accepting input from the user. By defualt the input is stored as character data type. For example :

In [2]:
user_name <- readline(prompt="Please Enter your name: ")

Please Enter your name: Louis de Broglie


In [3]:
# printing output stored in variable
print(user_name)

[1] "Louis de Broglie"


## Variables:
These are the containers which store the values in it. These variables or containers can hold different types of data values or data types in them. 

### Data Types in R :
There are many different types of data types objects in R, which are :
1. **Boolean :** Logical values - `TRUE` or `FALSE`
2. **Characters :** Strings or characters - `"Z"` , `"Welcome!"`
3. **Numeric :** Decial or Real values - `3.14`, `4`
4. **Integers :** Non decimal numbers - `4L`  
5. **Complex :** real + Imaginary numbers - `3+9i` ( Of the form: a+bi )


Lets create a string with variable name- 'greet' :

In [4]:
# 1. 
var_bool <- TRUE
# 2. 
var_greet <- "Welcome!"
# 3.
var_number <- 3.14
# 4.
var_int <- 4L
# 5.
var_cmplx <- 3+9i

To check the datatype of a variable we use the `typeof()` function. For example to check datatype of var_bool :

In [5]:
# Types of : 
# 1.
print("Type of var_bool : ")
typeof(var_bool)
# 2.
print("Type of var_greet : ")
typeof(var_greet)
# 3.
print("Type of var_number : ")
typeof(var_number)
# 4.
print("Type of var_int : ")
typeof(var_int)
# 5.
print("Type of var_cmplx : ")
typeof(var_cmplx)

[1] "Type of var_bool : "


[1] "logical"

[1] "Type of var_greet : "


[1] "character"

[1] "Type of var_number : "


[1] "double"

[1] "Type of var_int : "


[1] "integer"

[1] "Type of var_cmplx : "


[1] "complex"

## Variable Assignment operators:
The values to the variables can be assigned in three different ways :

|Assignment type|Syntax|
|--|--|
|**Leftward** operator | `[variable] <- [value]`|
|**Rightward** operator|`    [value] -> [variable]`|
|**Equals to** operator|` [variable] =  [value]`|


In [6]:
# 1. 
var_num <- 15.36
cat("Leftward  : ",var_num,"\n")

# 2. 
999.9 -> var_num
cat("Rightward : ",var_num,"\n")

# 3. 
var_num = 2L
cat("Equals to : ",var_num,"\n")

Leftward  :  15.36 
Rightward :  999.9 
Equals to :  2 


## Different Operator types:
There are different types of operators :

### 1. **Arithmetic Operators:**
Arithmetic operations includes : 

| Arithmetic Operator | |
|--|--|
|**+**| Addition|
|**-**| Subtraction|
|**\***| Multiplication|
|**/**| Division|
|**%%**| Remainder|
|**^**| Exponent|
|**%/%**| Quotient|

For example :

In [7]:
var_num <- 44                     # Assignment 
cat("var_num =", var_num,"\n")

var_num = var_num + 6             # 44 + 6
cat("var_num =", var_num,"\n")

var_num = var_num - 20            # 50 - 20
cat("var_num =", var_num,"\n")

var_num = var_num * 2            # 30*2
cat("var_num =", var_num,"\n")

var_num = var_num / 3             # 60 / 3 
cat("var_num =", var_num,"\n")

var_num = var_num ^ 2             # 20^2 = 20*20 
cat("var_num =", var_num,"\n")

var_num = var_num %% 5             # 400 is divisible by 5. Hence Remainder = 0
cat("var_num =", var_num,"\n")

var_num <-400
var_num = var_num %/% 5            # when 400 / 5. Quotient = 80
cat("var_num =", var_num,"\n")

var_num = 44 
var_num = 50 
var_num = 30 
var_num = 60 
var_num = 20 
var_num = 400 
var_num = 0 
var_num = 80 


### 2. **Comparison Operators:**
This includes : 
| Relational Operator | |
|--|--|
|**<**| Less than |
|**>**| More than|
|**<=**| Less than equal|
|**>=**| Greator than equal|
|**==**| Equals |
|**!=**| Not Equals|

In [8]:
var_res <- 400 < 200
cat("400    <   200 =", var_res,"\n\n")

var_res <- 200 >= 200
cat("200    >=  200 =", var_res,"\n\n")

var_res <- 200%%2 != 0 
cat("200%%2 ==   0  =", var_res,"\n\n")

var_res <- 33 == 22
cat("33     !=   22 =", var_res,"\n")


400    <   200 = FALSE 

200    >=  200 = TRUE 

200%%2 ==   0  = FALSE 

33     !=   22 = FALSE 


### 3. **Logical Operators:**
These are used when we want to compare multiple conditions returning a boolean value. This includes : 
| Logical Operator | |
|--|--|
|**\|\|**| Logical OR |
|**!**| Logical NOT|
|**&&**| Logical AND|

For example consider :

In [9]:
# True  OR   FALSE  = TRUE
5<9     ||   1>2

[1] TRUE

In [10]:
# True  AND  FALSE  = FALSE
5<9     &&   1>2

[1] FALSE

In [11]:
# 1 is not equal to 5 = TRUE
1 != 5

[1] TRUE

### 4. **Membership Operators:**

| Membership Operator | |
|--|--|
|**%in%**| Used to check if an element is present in other object |


In [12]:
var_vector = c(1:5)
var_vector

[1] 1 2 3 4 5

In [13]:
# since number 5 is present in vector "var_vector" 
# output : TRUE

5 %in% var_vector

[1] TRUE

In [14]:
# since number 15 is NOT present in vector "var_vector" 
# output : FALSE

15 %in% var_vector

[1] FALSE

## Vectors :
Vector is a collection of multiple elements which are of the same datatype. 
These can be created using the `c()` function. 

In [15]:
# Vector example:
var_vector <- c(1,2,3,5,7)
print(var_vector)

# printing typeof vector 
print(typeof(var_vector))

[1] 1 2 3 5 7
[1] "double"


If a vector is created with different types of data type elements present inside then it forces the element to be a higher data type <br>i.e. **boolean < integer < double < character**.

Consider the following example: 

In [16]:
# Below is a vector with a single Integer number
var_vector <- c( 10L )
print(typeof(var_vector))

[1] "integer"


In [17]:
# below is a vector with a Integer number and a double number 
var_vector <- c( 10L , 3.14)
print(typeof(var_vector))

[1] "double"


In [18]:
# below is a vector with a Integer, double and a character datatype  
var_vector <- c( 10L , 3.14, "Pi value")
print(typeof(var_vector))

[1] "character"


## Lists :
List is an object which holds multiple elements like functions, vectors variables etc. It can be created using the `list()` function.

In [19]:
var_list <- list( 3.14, c(11,13,17), TRUE )
print(var_list)

[[1]]
[1] 3.14

[[2]]
[1] 11 13 17

[[3]]
[1] TRUE



**Each of the elements present in the list can be assigned names.**

For example in the above var_list if we want to assign each of the elements name as "pi value", "numbers","boolean" then:

In [20]:
# Assigniing names
names(var_list) <- c("pi value", "numbers","boolean" ) 

# Accessing the First element : pi value
var_list[1]

$`pi value`
[1] 3.14

#### Manipulating and Merging Lists:

First Lets create a list with multiple types of elements:

In [21]:
# Creating List :
var_list <- list( list("pi",3.14), c("Pizza","Burger","Vada Pav"), matrix(c(1,2,3,4), nrow = 2)) 
cat("The length of list = ",length(var_list),"\n\n")
print(var_list)

The length of list =  3 

[[1]]
[[1]][[1]]
[1] "pi"

[[1]][[2]]
[1] 3.14


[[2]]
[1] "Pizza"    "Burger"   "Vada Pav"

[[3]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4



**1. Adding a new element at the end of the list :**

In [22]:
cat("The length of list before appending = ",length(var_list),"\n\n")
var_list[length(var_list)+1] = list(list("Golden ratio",1.618))
cat("The length of list after  appending = ",length(var_list),"\n\nList :")
print(var_list)

The length of list before appending =  3 

The length of list after  appending =  4 

List :[[1]]
[[1]][[1]]
[1] "pi"

[[1]][[2]]
[1] 3.14


[[2]]
[1] "Pizza"    "Burger"   "Vada Pav"

[[3]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[4]]
[[4]][[1]]
[1] "Golden ratio"

[[4]][[2]]
[1] 1.618




**2. Removing First Element of list :**

By assigning NULL to an list index will remove that element present at that index. 

In [23]:
cat("The length of list before removing first element = ",length(var_list),"\n")

The length of list before removing first element =  4 


In [24]:
var_list[1] <- NULL
cat("The length of list after removing first element = ",length(var_list),"\n\nList :")
print(var_list)

The length of list after removing first element =  3 

List :[[1]]
[1] "Pizza"    "Burger"   "Vada Pav"

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[[3]][[1]]
[1] "Golden ratio"

[[3]][[2]]
[1] 1.618




**3. Merging two lists :**

In [25]:
physical_constants = list( 299792458, 1.602*10^(−19), 6.626*10^(−34) )
chemical_constants = list( 6.022*10^(23), 96485.33, 8.314, 8.987*10^9, 9.806 )

# Lets add physical and chemical constants to a single list contaning all the constants :
all_constants <- c(physical_constants, chemical_constants)

# Display physical_constants
cat("Physical constants are :\n\n")
physical_constants

# Display chemical_constants
cat("Chemical constants are :\n\n")
chemical_constants

# dispaly all_constants
cat("All constants are :\n\n")
all_constants

Physical constants are :



[[1]]
[1] 299792458

[[2]]
[1] 1.602e-19

[[3]]
[1] 6.626e-34

Chemical constants are :



[[1]]
[1] 6.022e+23

[[2]]
[1] 96485.33

[[3]]
[1] 8.314

[[4]]
[1] 8.987e+09

[[5]]
[1] 9.806

All constants are :



[[1]]
[1] 299792458

[[2]]
[1] 1.602e-19

[[3]]
[1] 6.626e-34

[[4]]
[1] 6.022e+23

[[5]]
[1] 96485.33

[[6]]
[1] 8.314

[[7]]
[1] 8.987e+09

[[8]]
[1] 9.806

#### Convert Lists to vectors:
We use the unlist() to create a vector which contains all the atomic componens occuring in the given list.

In [26]:
# Creating the lists:
var_list1 <- list(10, 12, 15)
var_list2 <- list(2, 4, 6)

# Checking Class type of above lists: 
cat("Class Type of var_list1 -> ",class(var_list1),"\n")
cat("Class Type of var_list2 -> ",class(var_list2),"\n\n")

# Converting lists to vector using the unlist() function:
vec1 <- unlist(var_list1)
vec2 <- unlist(var_list2)

# Checking Class type of newly created vectors: 
cat("Vector 1 :")
print(vec1)
cat("\n\nVector 2 :")
print(vec2)

# Adding the to vectors 
cat("\n\nAddition Result : ")
print(vec2 + vec1)

Class Type of var_list1 ->  list 
Class Type of var_list2 ->  list 

Vector 1 :[1] 10 12 15


Vector 2 :[1] 2 4 6


Addition Result : [1] 12 16 21


## Matrices :
These are the 2-dimensional arrays arranged in the form of rows and columns, which can be created using the `matrix()` function.

For example:


In [27]:
# Creating a matrix of dimension (8,1)  
var_vector <- c(1:8)
var_matrix <- matrix( var_vector )
print(var_matrix)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6
[7,]    7
[8,]    8


In [28]:
# Matrix of dimenson (4,2)
var_vector <- c(1:8)
var_matrix <- matrix( var_vector, nrow=4,ncol=2 )
print(var_matrix)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


**Matrix Operations:**

First, Lets create two matrices:

In [29]:
# Creating the two matrices
mat1 <- matrix(c(-8,-4,-2,0,2,4), nrow=3)
mat2 <- matrix(c(1,2,2,0,1,3), nrow=3)

cat("Matrix 1 : \n\n")
print(mat1)

cat("\nMatrix 2 : \n\n")
print(mat2)

Matrix 1 : 

     [,1] [,2]
[1,]   -8    0
[2,]   -4    2
[3,]   -2    4

Matrix 2 : 

     [,1] [,2]
[1,]    1    0
[2,]    2    1
[3,]    2    3


**1. Addition, Subtraction:**

In [30]:
cat("Addition Result : \n\n")
print(mat1 + mat2)

cat("\n\nSubtraction Result:\n\n")
print(mat1 - mat2)

Addition Result : 

     [,1] [,2]
[1,]   -7    0
[2,]   -2    3
[3,]    0    7


Subtraction Result:

     [,1] [,2]
[1,]   -9    0
[2,]   -6    1
[3,]   -4    1


**2. Element wise Multiplication and Division :**

In [31]:
cat("\n\nMultiplication Result:\n\n")
print(mat1 * mat2)

cat("\n\nDivision Result:\n\n")
print(mat1 / mat2)



Multiplication Result:

     [,1] [,2]
[1,]   -8    0
[2,]   -8    2
[3,]   -4   12


Division Result:

     [,1]     [,2]
[1,]   -8      NaN
[2,]   -2 2.000000
[3,]   -1 1.333333


**Matrix multiplication :**

Syntax : `<matrix 1> %*% <matrix 2>`

In [32]:
# Creating two matrices :
# matrix 1 with 4 rows and 3 columns
mat1 <- matrix(1:12, ncol = 3, nrow = 4)

# matrix 2 with 3 rows and 4 columns
mat2 <- matrix(rep(1,12), ncol = 4, nrow = 3)

cat("Matrix 1 : \n\n")
print(mat1)

cat("\nMatrix 2 : \n\n")
print(mat2)

cat("\n\nMatrix Multiplication Result:\n\n")
print(mat1 %*% mat2)

Matrix 1 : 

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

Matrix 2 : 

     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1    1    1
[3,]    1    1    1    1


Matrix Multiplication Result:

     [,1] [,2] [,3] [,4]
[1,]   15   15   15   15
[2,]   18   18   18   18
[3,]   21   21   21   21
[4,]   24   24   24   24


## Arrays :
These are the multi-dimensional arrays arranged in the form of rows, column and depth, which can be created using the `array()` function.

For example: creating a three dimensional array with two layers of (1,3) matrix values: (11,22,33)  

of the form :
```
[ 
  [ 11 , 22 , 33 ],
  [ 11 , 22 , 33 ]
]

```

In [33]:
var_arr <- array(c(11,22,33),dim= c(1,3,2))
print(var_arr)

, , 1

     [,1] [,2] [,3]
[1,]   11   22   33

, , 2

     [,1] [,2] [,3]
[1,]   11   22   33



**Naming Rows and Columns of Arrays:**

In [34]:
# Creating row and column names vectors:
row_names = c("row_1","row_2","row_3")
col_names = c("col_1","col_2","col_3")

# Creating the array with row and column names:
arr1 <- array( 1:9, 
            dim=c(3,3),
            dimnames= list(row_names, col_names)
            )
cat("Array :\n\n")
print(arr1)

Array :

      col_1 col_2 col_3
row_1     1     4     7
row_2     2     5     8
row_3     3     6     9


## if - else - switch statements :
These statements are responsible for checking if a set of conditions specified are TRUE or FALSE. These statements are resposible for controling the flow of code execution.  

### 1. **if statement:**

**Syntax :**
```
if ( [ condition ] ){
    # Block of code to execute
    # if condition is TRUE 
}
```
Consider example:

In [35]:
# Checking if 33 is divible by 3

var_num = 33
if (var_num %% 3==0){
    cat(var_num," is divisible by 3!\n")
}

33  is divisible by 3!


### 2. **if - else statement:**

**Syntax :**
```
if ( [ condition ] ){
    # Block of code to execute
    # if condition is TRUE 
} else {    #<------------------------------ PLEASE NOTE THIS SYNTAX
                                           # If this is not followed,
    # Block of code to execute             # then it will raise errors
    # if condition is FALSE 
}
```
Consider example:

In [36]:
# Checking if numebr 2 is divisible by 3 .

var_num = 2
if (var_num %% 3==0){
    cat(var_num," is divisible by 3!\n")
} else {
    cat(var_num," NOT divisible by 3!\n")
}

2  NOT divisible by 3!


### 3. **Switch statement:**

**Syntax :**
```
switch ( [choice], case1, case2, case3,...)

returns case
```


Consider example :

In [37]:
var_choice = 8

switch(var_choice, "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X")


[1] "VIII"

## Loop Statements:

There are 3 types of looping constructs, which are :

| | loop name|
|--|:-|
|**1.**|**for loop**|
|**2.**|**while loop**|
|**3.**|**repeat loop**|

### 1. **for loop:**

**Syntax :**
```
for ( item in vector ) {
    # Block of statemenst to execute
    # for each loop-item
}
```
Consider example:

In [38]:
# print Multiplication Table for number : 11
var_num = 11
cat("Multiplication Table for ",var_num," is as follows: \n\n")

for ( var_item in 1:10){
    cat(var_num," * ",var_item," = ",(var_num*var_item),"\n")
}

Multiplication Table for  11  is as follows: 

11  *  1  =  11 
11  *  2  =  22 
11  *  3  =  33 
11  *  4  =  44 
11  *  5  =  55 
11  *  6  =  66 
11  *  7  =  77 
11  *  8  =  88 
11  *  9  =  99 
11  *  10  =  110 


In [39]:
# Another example:
restaurants = c( "McDonald", "Subway", "Starbucks", "Pizza Hut")
cat("Famous and biggest fast Food Chains are :\n\n")

for ( item in restaurants ){
    cat(item,"\n")
}

Famous and biggest fast Food Chains are :

McDonald 
Subway 
Starbucks 
Pizza Hut 


### 2. **while loop:**
**Syntax :**
```
while ( conditions ) {
    # Block of statements to execute
    # while the above condition is TRUE
}
```

So, an example for this :

In [40]:
# Checking even numbers between 1 and 15
var_counter = 1
while ( var_counter < 15 ){
    if (var_counter%%2 == 0 ){
        cat(var_counter," is a even number!\n")
    }
    var_counter=var_counter+1
}

2  is a even number!
4  is a even number!
6  is a even number!
8  is a even number!
10  is a even number!
12  is a even number!
14  is a even number!


### 3. **repeat loop:**
This looping construct is almost similar to the functioning of the while loop, but please note the syntax : 

**Syntax :**
```
repeat {
    
    # Block of statements to execute repeatedly
    
    if ( condition ){
        # Block of statements to execute 
        # before exiting the repeatloop
        break
    }
}
```

So, an example for this :


In [41]:
# Checking even numbers between 1 and 15
var_counter = 1

repeat {
    if (var_counter%%2 == 0 ){
        cat(var_counter," is a even number!\n")
    }

    var_counter = var_counter + 1

    if( var_counter > 15) {
        cat("\nExiting repeat loop.")
        break
    }
}

2  is a even number!
4  is a even number!
6  is a even number!
8  is a even number!
10  is a even number!
12  is a even number!
14  is a even number!

Exiting repeat loop.

## Loop Control statements :

There 2 types of loop control statements:

| | loop control name |use|
|--|:-|--|
|**1.**|**break statement**|terminate loop execution|
|**2.**|**next statement** |skip loop execution to next counter |

### 1. break :

In [42]:
# [ break ]
# break loop when var_counter > 9

for ( var_counter in 1:20 ){
    cat(var_counter,"\n")
    if ( var_counter > 9 ){
        break
    }
}

1 
2 
3 
4 
5 
6 
7 
8 
9 
10 


### 2. next :

In [43]:
# [ next ]
# when '!' and '.' is encontered skip them and print a space ' ' instead.

for ( var_char in c("Hi","!", "Welcome",".", "See you later","!",".") ){
    
    if ( (var_char == ".") || (var_char == "!") ){
        cat(" ")
        next
    }
    cat(var_char)
}

Hi Welcome See you later  

## Functions:

These are blocks of code which run only when they are called. This is mostly used when wanting to reuse same code multiple times across the code.

**Syntax:**

**Function Definition :**
```
[function name] <- function( param1, param2, param3, ... ) {

    # Define body of function 
    # [ Blocks of code ]

    # return statement [optional] 
}
```
**Function calling:**
`>> [function name]( param1, param2, param3, ... )`

For example consider for **swaping two numbers:**

In [44]:
# Function defenition:
swap_2_num <- function( var1, var2) {
    var_temp <- var1
    var1 <- var2
    var2 <-var_temp
    return(c(var1,var2))
}

In [45]:
# User input for two numbers and swapping these numebrs

var1 <- as.integer(readline(prompt="Enter your First number  : "))
var2 <- as.integer(readline(prompt="Enter your Second number : "))

cat("\nThe numbers before swap are : \nA = ",var1,"  | B = ",var2,"\n\n")
cat("swappping!\n\n")

values = swap_2_num(var1,var2)

cat("The numbers before swap are : \nA = ",values[1],"  | B = ",values[2],"\n\n")

Enter your First number  : 19
Enter your Second number : 33

The numbers before swap are : 
A =  19   | B =  33 

swappping!

The numbers before swap are : 
A =  33   | B =  19 



### Functions with default parameters:

For example:

In [46]:
# function for multiplying two numbers 
multiply <- function(a,b=1){
    return(a*b)
}

# multiplying two numbers
result = multiply(5,10)     # 5 * 10
cat("result1 = ",result,"\n")

result = multiply(5)        # 5 * 1(default value when not specified in parameter) 
cat("result2 = ",result,"\n")

result1 =  50 
result2 =  5 


## String Manipulations :

### I. toupper() and tolower() function:
|function name|use|
|--|--|
|**toupper()**| To capitalise all the letters present in your string.|
|**tolower()**|To change all the letters present in your string to lower case letters.|

For example:

In [47]:
var_string = "Bottled Fresh Juices. Buy 1 get 1 Free!"

cat("Original   string = ",(var_string),"\n\n")
cat("Upper case string = ",toupper(var_string),"\n\n")
cat("Lower case string = ",tolower(var_string))

Original   string =  Bottled Fresh Juices. Buy 1 get 1 Free! 

Upper case string =  BOTTLED FRESH JUICES. BUY 1 GET 1 FREE! 

Lower case string =  bottled fresh juices. buy 1 get 1 free!

### II. Sub-String \[ substring() / substr() \] :

This function is used in order to extract specific slice from a string.

**Syntax:**

`substring( string_value, start, stop )`

or

`substr( string_value, start, stop )   `


An example :

In [48]:
# applying substring on a string slicing from 5th to 10th index

substring("watermelon",5,10)   # or substr("watermelon",5,10)

[1] "rmelon"

In [49]:
# applying substring on a vector of elements
x <- c("strawberry", "apple", "mango")
substr(x, 3, 5)

[1] "raw" "ple" "ngo"

### III. String concatenation \[ paste function \] :

**paste()** is a function used for concatenation of multiple strings into a single string.

**Syntax:**

`paste( str1, str2, str3, ... , sep=[separator value], collapse= [collapse value])`

|parameter| use |default|
|--|--|--|
|**sep**|Used to show the separation between the strings passed as parameters|`' '`|
|**collapse**|Used to remove the space between two strings|`NULL`|

Consider Example:

In [50]:
# Example for paste - sep :
str1 <- "Hi!"
str2 <- "Welcome back!"
str3 <- "How are you?"

paste(str1,str2,str3,sep="______")

[1] "Hi!______Welcome back!______How are you?"

In [51]:
# Example for paste - collapse :
paste(c("L", "M", "N"), 
      c("O", "P", "Q"), collapse = '')

[1] "L OM PN Q"

## Comments:
These are the additional text that is added to explain the written code. It is mainly used to make the code more understandable. Comments can be written either in a single line or across multiple lines.

### 1. **Single Line comments**:
This is written by typing a ' # ' at the start of the line. For example:



In [52]:
# This is a single line comment.

### 2. **MultiLine comments:** 
This is  written by enclosing the text in a false if condition.

In [53]:
if (FALSE){
    "This is a multiline comment enclosed 
        in an False if condition."
}

### Data Frames:
This is data stored in the form of rows and column as in a matrix such that each column contains a different type of data and each row is indexed.

**For example:** *consider the following dataframe which has data about housing:*

In [54]:
house_data <- data.frame(
    name     = c( "Beverly Hills", "Bright sunshine", "Golden Mist","Konoha"),
    location = c( "Pashan", "Baner", "Aundh", "Pimpri" ),
    bedrooms = c( 2, 1, 3, 2),
    bathrooms= c( 2, 1, 4, 1),
    kitchen  = c( 1, 1, 2, 1),
    family_only= c( TRUE, FALSE, TRUE, TRUE),
    price    = c( 10000, 7000 , 25000, 9000)
)

house_data

name            location bedrooms bathrooms kitchen family_only price
1 Beverly Hills   Pashan   2        2         1        TRUE       10000
2 Bright sunshine Baner    1        1         1       FALSE        7000
3 Golden Mist     Aundh    3        4         2        TRUE       25000
4 Konoha          Pimpri   2        1         1        TRUE        9000

#### Structure of DataFrame:
To get the structure of our DataFrame:

In [55]:
str(house_data)

'data.frame':	4 obs. of  7 variables:
 $ name       : Factor w/ 4 levels "Beverly Hills",..: 1 2 3 4
 $ location   : Factor w/ 4 levels "Aundh","Baner",..: 3 2 1 4
 $ bedrooms   : num  2 1 3 2
 $ bathrooms  : num  2 1 4 1
 $ kitchen    : num  1 1 2 1
 $ family_only: logi  TRUE FALSE TRUE TRUE
 $ price      : num  10000 7000 25000 9000


#### Summary of DataFrame:
To get the summary of our DataFrame we use the summary() function and pass the Dataframe as an argument to it :

In [56]:
summary(house_data)

              name     location    bedrooms      bathrooms      kitchen    
 Beverly Hills  :1   Aundh :1   Min.   :1.00   Min.   :1.0   Min.   :1.00  
 Bright sunshine:1   Baner :1   1st Qu.:1.75   1st Qu.:1.0   1st Qu.:1.00  
 Golden Mist    :1   Pashan:1   Median :2.00   Median :1.5   Median :1.00  
 Konoha         :1   Pimpri:1   Mean   :2.00   Mean   :2.0   Mean   :1.25  
                                3rd Qu.:2.25   3rd Qu.:2.5   3rd Qu.:1.25  
                                Max.   :3.00   Max.   :4.0   Max.   :2.00  
 family_only         price      
 Mode :logical   Min.   : 7000  
 FALSE:1         1st Qu.: 8500  
 TRUE :3         Median : 9500  
                 Mean   :12750  
                 3rd Qu.:13750  
                 Max.   :25000  

#### Getting all the column names : 


In [57]:
names(house_data)

[1] "name"        "location"    "bedrooms"    "bathrooms"   "kitchen"    
[6] "family_only" "price"

#### Getting total number of rows in our dataframe:

We use the `nrow()` function by passing out dataframe to it which then return us the number of rows present in that dataframe.

In [58]:
cat("Total number of rows in our dataframe = ",nrow(house_data))

Total number of rows in our dataframe =  4

#### Accessing Rows and Columns:

1. **Rows :**

For example, if we wanted to get the 2nd and 3rd rows of our dataframe then we do it as follows :

In [59]:
house_data[2:3,]

name            location bedrooms bathrooms kitchen family_only price
2 Bright sunshine Baner    1        1         1       FALSE        7000
3 Golden Mist     Aundh    3        4         2        TRUE       25000

**2. Columns :**

For example, if we wanted to access or get all the values present in the 'location' column of the House dataframe above then, we specify the column name after a dollor sign ($) added at the end of the dataframe variable name as follows:

Syntax :  `<dataframe name>$<column name>`

In [60]:
house_data$location

[1] Pashan Baner  Aundh  Pimpri
Levels: Aundh Baner Pashan Pimpri

Or if you want to access multiple columns then :

In [61]:
house_data[c('name','bedrooms','location')]

name            bedrooms location
1 Beverly Hills   2        Pashan  
2 Bright sunshine 1        Baner   
3 Golden Mist     3        Aundh   
4 Konoha          2        Pimpri

#### Adding new Rows and Columns in our DataFrame :

**1. Adding new Rows :**

By creating a new temporary Dataframe and appending it :

In [62]:
# Creating a list containing all the new row values to be added 
new_row_value <- list("Serene Waves", "Lonavala",2,1,1,FALSE,13000)

# Creating a temporary dataframe with the new row values  
temp_df <- data.frame( new_row_value )

# Renaming all the columns in the temporary dataframe to match the column names in our house dataframe
names(temp_df) <- names(house_data) 

# Using the ribnd() function to add this temporary dataframe at the end of teh source dataframe 
house_data <- rbind(house_data, temp_df)

# Display house_data
house_data

name            location bedrooms bathrooms kitchen family_only price
1 Beverly Hills   Pashan   2        2         1        TRUE       10000
2 Bright sunshine Baner    1        1         1       FALSE        7000
3 Golden Mist     Aundh    3        4         2        TRUE       25000
4 Konoha          Pimpri   2        1         1        TRUE        9000
5 Serene Waves    Lonavala 2        1         1       FALSE       13000

**2. Adding new Columns :**

Lets try adding a isMaintenance column for the houses in our DataFrame:

In [63]:
# Create maintenance vector corresponding to each house.
maintenance <- c(TRUE,FALSE,TRUE,TRUE,FALSE)

# Assign these house maintenance values to a new column named 'isMaintenance'
house_data$isMaintenance <- maintenance

# Display DataFrame
house_data

name            location bedrooms bathrooms kitchen family_only price
1 Beverly Hills   Pashan   2        2         1        TRUE       10000
2 Bright sunshine Baner    1        1         1       FALSE        7000
3 Golden Mist     Aundh    3        4         2        TRUE       25000
4 Konoha          Pimpri   2        1         1        TRUE        9000
5 Serene Waves    Lonavala 2        1         1       FALSE       13000
  isMaintenance
1  TRUE        
2 FALSE        
3  TRUE        
4  TRUE        
5 FALSE

## Functions:

#### 1. apply() function :  

In [64]:
# Creating matrix 
mat1 <- matrix(C<-(1:10),nrow=5, ncol=6)

cat("Matrix :\n\n")
print(mat1)

cat("\n\nResult after applying sum function :\n\n")
res <- apply(mat1, 2, sum)
print(res)

Matrix :

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    6    1    6    1    6
[2,]    2    7    2    7    2    7
[3,]    3    8    3    8    3    8
[4,]    4    9    4    9    4    9
[5,]    5   10    5   10    5   10


Result after applying sum function :

[1] 15 40 15 40 15 40


#### 2. factor() function:

The [factor()](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/factor) function is used to encode a vector as a factor.

Lets see an example:

In [65]:
# Creating the vector: 
labels <- c( "A","B","D","E","F","G","H" )
cat("Vector : \n\n")
print(labels)
cat("\nIs 'labels' vector factorized : ",is.factor(labels))

# Using the factor() function on our labels vector:
factor_labels <- factor(labels)
cat("\n\n\nFactorised Vector : \n\n")
print(factor_labels)
cat("\nIs 'factor_labels' vector factorized : ",is.factor(factor_labels))

Vector : 

[1] "A" "B" "D" "E" "F" "G" "H"

Is 'labels' vector factorized :  FALSE


Factorised Vector : 

[1] A B D E F G H
Levels: A B D E F G H

Is 'factor_labels' vector factorized :  TRUE

**Changing the Order of the Levels :**

In [66]:
# Creating the vector: 
drinks <- c("Cola","Pepsi","Pepsi", "7up","7up","Cola")
cat("drinks vector : \n\n")
print(drinks)

# Factorizing teh drink vector:
factor_drinks <- factor(drinks)
cat("\n\nFactorized drinks vector : \n\n")
print(factor_drinks)

# Again we apply the factor() for changing the order of the levels:
result <- factor(factor_drinks, levels=c("Pepsi", "7up","Cola"))
cat("\n\nFinal result with changed order of levels: \n\n")
print(result)

drinks vector : 

[1] "Cola"  "Pepsi" "Pepsi" "7up"   "7up"   "Cola" 


Factorized drinks vector : 

[1] Cola  Pepsi Pepsi 7up   7up   Cola 
Levels: 7up Cola Pepsi


Final result with changed order of levels: 

[1] Cola  Pepsi Pepsi 7up   7up   Cola 
Levels: Pepsi 7up Cola


#### 3. gl() function:

The [gl()](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/gl) function is used to create factors by specifying the pattern of their levels.

Consider an Example:

In [67]:
# Example-1
sentiments <- gl(4,3, labels=c("negative","neutral","positive","None"))
print(sentiments)

 [1] negative negative negative neutral  neutral  neutral  positive positive
 [9] positive None     None     None    
Levels: negative neutral positive None


In [68]:
# Example-2
# Alternating pairs of ( 1, 2, 3, and 4 ) with total length = 20 
print(gl(4,2,20))

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2
Levels: 1 2 3 4


<hr>